// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Buying Refinancing Process documents */
interface BuyingRefinancingProcessDocumentData {
  /**
   * Title field in *Buying Refinancing Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: buying_refinancing_process.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Text field in *Buying Refinancing Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: buying_refinancing_process.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text: prismicT.KeyTextField;
  /**
   * Second Text field in *Buying Refinancing Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: buying_refinancing_process.second_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  second_text: prismicT.KeyTextField;
  /**
   * third_text field in *Buying Refinancing Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: buying_refinancing_process.third_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  third_text: prismicT.KeyTextField;
  /**
   * Icon1 field in *Buying Refinancing Process*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: buying_refinancing_process.icon1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon1: prismicT.ImageField<never>;
  /**
   * Icon2 field in *Buying Refinancing Process*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: buying_refinancing_process.icon2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon2: prismicT.ImageField<never>;
}
/**
 * Buying Refinancing Process document from Prismic
 *
 * - **API ID**: `buying_refinancing_process`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BuyingRefinancingProcessDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<BuyingRefinancingProcessDocumentData>,
    "buying_refinancing_process",
    Lang
  >;
/** Content for Circle Grid Info documents */
interface CircleGridInfoDocumentData {
  /**
   * Text1 field in *Circle Grid Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.text1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text1: prismicT.KeyTextField;
  /**
   * Text2 field in *Circle Grid Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.text2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text2: prismicT.KeyTextField;
  /**
   * Text3 field in *Circle Grid Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.text3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text3: prismicT.KeyTextField;
  /**
   * Text4 field in *Circle Grid Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.text4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text4: prismicT.KeyTextField;
  /**
   * Text5 field in *Circle Grid Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.text5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text5: prismicT.KeyTextField;
  /**
   * Text6 field in *Circle Grid Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.text6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text6: prismicT.KeyTextField;
  /**
   * Text7 field in *Circle Grid Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.text7
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text7: prismicT.KeyTextField;
  /**
   * Text8 field in *Circle Grid Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.text8
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text8: prismicT.KeyTextField;
  /**
   * Text Central field in *Circle Grid Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.text_central
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text_central: prismicT.KeyTextField;
  /**
   * Image field in *Circle Grid Info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: circle_grid_info.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Circle Grid Info document from Prismic
 *
 * - **API ID**: `circle_grid_info`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CircleGridInfoDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<CircleGridInfoDocumentData>,
    "circle_grid_info",
    Lang
  >;
/** Content for Contact documents */
interface ContactDocumentData {
  /**
   * Number Field field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.number_field
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  number_field: prismicT.KeyTextField;
}
/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;
/** Content for Footer documents */
interface FooterDocumentData {
  /**
   * Instagram field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  instagram: prismicT.KeyTextField;
  /**
   * Email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  email: prismicT.KeyTextField;
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
  /**
   * Team field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.team
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  team: prismicT.ImageField<never>;
  /**
   * Footer Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  footer_text: prismicT.KeyTextField;
  /**
   * Instagram Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.instagram_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  instagram_logo: prismicT.ImageField<never>;
  /**
   * Instagram Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.instagram_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  instagram_link: prismicT.LinkField;
  /**
   * Facebook Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  facebook_logo: prismicT.ImageField<never>;
  /**
   * Facebook Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  facebook_link: prismicT.LinkField;
  /**
   * TikTok Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.tiktok_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  tiktok_logo: prismicT.ImageField<never>;
  /**
   * TikTok Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.tiktok_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  tiktok_link: prismicT.LinkField;
  /**
   * Youtube Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.youtube_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  youtube_logo: prismicT.ImageField<never>;
  /**
   * Youtube Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.youtube_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  youtube_link: prismicT.LinkField;
}
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for General Information documents */
interface GeneralInformationDocumentData {
  /**
   * Small Logo field in *General Information*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.small_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  small_logo: prismicT.ImageField<never>;
  /**
   * Small Logo Width field in *General Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.small_logo_width
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  small_logo_width: prismicT.KeyTextField;
  /**
   * Small Logo Height field in *General Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.small_logo_height
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  small_logo_height: prismicT.KeyTextField;
  /**
   * We Work Text field in *General Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.we_work_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  we_work_text: prismicT.KeyTextField;
  /**
   * Twentyfourseven Text field in *General Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.twentyfourseven_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  twentyfourseven_text: prismicT.KeyTextField;
  /**
   * Powered Text field in *General Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.powered_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  powered_text: prismicT.KeyTextField;
  /**
   * Dadeland Text field in *General Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.dadeland_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  dadeland_text: prismicT.KeyTextField;
  /**
   * Difference Text field in *General Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.difference_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  difference_text: prismicT.KeyTextField;
  /**
   * Upside Button Message field in *General Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.upside_button_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  upside_button_message: prismicT.KeyTextField;
  /**
   * Button Message field in *General Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_information.button_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_message: prismicT.KeyTextField;
}
/**
 * General Information document from Prismic
 *
 * - **API ID**: `general_information`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GeneralInformationDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<GeneralInformationDocumentData>,
    "general_information",
    Lang
  >;
/** Content for Homepage documents */
type HomepageDocumentData = Record<string, never>;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for Meet Team documents */
interface MeetTeamDocumentData {
  /**
   * Title field in *Meet Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Subtitle field in *Meet Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismicT.KeyTextField;
  /**
   * Text1 field in *Meet Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.text1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text1: prismicT.KeyTextField;
  /**
   * Text2 field in *Meet Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.text2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text2: prismicT.KeyTextField;
  /**
   * Text3 field in *Meet Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.text3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text3: prismicT.KeyTextField;
  /**
   * Slice Zone field in *Meet Team*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_team.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<MeetTeamDocumentDataSlicesSlice>;
}
/**
 * Slice for *Meet Team → Slice Zone*
 *
 */
type MeetTeamDocumentDataSlicesSlice = never;
/**
 * Meet Team document from Prismic
 *
 * - **API ID**: `meet_team`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MeetTeamDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<MeetTeamDocumentData>,
    "meet_team",
    Lang
  >;
/** Content for Member documents */
interface MemberDocumentData {
  /**
   * Name field in *Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Surname field in *Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.surname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  surname: prismicT.KeyTextField;
  /**
   * Position field in *Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  position: prismicT.KeyTextField;
  /**
   * NMLS field in *Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.nmls
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  nmls: prismicT.KeyTextField;
  /**
   * Email field in *Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  email: prismicT.KeyTextField;
  /**
   * Phone field in *Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  phone: prismicT.KeyTextField;
  /**
   * Instagram field in *Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  instagram: prismicT.KeyTextField;
  /**
   * Photo field in *Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: member.photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  photo: prismicT.ImageField<never>;
  /**
   * Slice Zone field in *Member*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: member.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<MemberDocumentDataSlicesSlice>;
}
/**
 * Slice for *Member → Slice Zone*
 *
 */
type MemberDocumentDataSlicesSlice = never;
/**
 * Member document from Prismic
 *
 * - **API ID**: `member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<MemberDocumentData>, "member", Lang>;
/** Content for Menú documents */
interface MenuDocumentData {
  /**
   * Menu Links field in *Menú*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  menu_links: prismicT.GroupField<Simplify<MenuDocumentDataMenuLinksItem>>;
}
/**
 * Item in Menú → Menu Links
 *
 */
export interface MenuDocumentDataMenuLinksItem {
  /**
   * Link field in *Menú → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  link: prismicT.KeyTextField;
  /**
   * Label field in *Menú → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
}
/**
 * Menú document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<MenuDocumentData>, "menu", Lang>;
/** Content for NON QM LOANS documents */
interface NonQmLoansDocumentData {
  /**
   * Title Text field in *NON QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.title_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_text: prismicT.KeyTextField;
  /**
   * Subtitle Text field in *NON QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.subtitle_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle_text: prismicT.KeyTextField;
  /**
   * Loan1 Image field in *NON QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan1_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan1_image: prismicT.ImageField<never>;
  /**
   * Loan1 Title field in *NON QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan1_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan1_title: prismicT.KeyTextField;
  /**
   * Loan1 Description field in *NON QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan1_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan1_description: prismicT.RichTextField;
  /**
   * Loan2 Image field in *NON QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan2_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan2_image: prismicT.ImageField<never>;
  /**
   * Loan2 Title field in *NON QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan2_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan2_title: prismicT.KeyTextField;
  /**
   * Loan2 Description field in *NON QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan2_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan2_description: prismicT.RichTextField;
  /**
   * Loan3 Image field in *NON QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan3_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan3_image: prismicT.ImageField<never>;
  /**
   * Loan3 Title field in *NON QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan3_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan3_title: prismicT.KeyTextField;
  /**
   * Loan3 Description field in *NON QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan3_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan3_description: prismicT.RichTextField;
  /**
   * Loan4 Image field in *NON QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan4_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan4_image: prismicT.ImageField<never>;
  /**
   * Loan4 Title field in *NON QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan4_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan4_title: prismicT.KeyTextField;
  /**
   * Loan4 Description field in *NON QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan4_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan4_description: prismicT.RichTextField;
  /**
   * Loan5 Image field in *NON QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan5_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan5_image: prismicT.ImageField<never>;
  /**
   * Loan5 Title field in *NON QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan5_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan5_title: prismicT.KeyTextField;
  /**
   * Loan5 Description field in *NON QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.loan5_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan5_description: prismicT.RichTextField;
  /**
   * Other Services Title field in *NON QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.other_services_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  other_services_title: prismicT.KeyTextField;
  /**
   * Other Services Description field in *NON QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: non_qm_loans.other_services_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  other_services_description: prismicT.RichTextField;
}
/**
 * NON QM LOANS document from Prismic
 *
 * - **API ID**: `non_qm_loans`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NonQmLoansDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<NonQmLoansDocumentData>,
    "non_qm_loans",
    Lang
  >;
/** Content for Pre Approval Process documents */
interface PreApprovalProcessDocumentData {
  /**
   * Title field in *Pre Approval Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_approval_process.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Text field in *Pre Approval Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_approval_process.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text: prismicT.KeyTextField;
  /**
   * Icon1 field in *Pre Approval Process*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_approval_process.icon1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon1: prismicT.ImageField<never>;
  /**
   * Icon2 field in *Pre Approval Process*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_approval_process.icon2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon2: prismicT.ImageField<never>;
  /**
   * Second Text field in *Pre Approval Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_approval_process.second_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  second_text: prismicT.KeyTextField;
  /**
   * third_text field in *Pre Approval Process*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pre_approval_process.third_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  third_text: prismicT.KeyTextField;
}
/**
 * Pre Approval Process document from Prismic
 *
 * - **API ID**: `pre_approval_process`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PreApprovalProcessDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<PreApprovalProcessDocumentData>,
    "pre_approval_process",
    Lang
  >;
/** Content for QM LOANS documents */
interface QmLoansDocumentData {
  /**
   * Title_text field in *QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.title_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_text: prismicT.KeyTextField;
  /**
   * Subtitle Text field in *QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.subtitle_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle_text: prismicT.KeyTextField;
  /**
   * Loan1 Image field in *QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan1_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan1_image: prismicT.ImageField<never>;
  /**
   * Loan1 Title field in *QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan1_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan1_title: prismicT.KeyTextField;
  /**
   * Loan1 Description field in *QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan1_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan1_description: prismicT.RichTextField;
  /**
   * Loan2 Image field in *QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan2_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan2_image: prismicT.ImageField<never>;
  /**
   * Loan2 Title field in *QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan2_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan2_title: prismicT.KeyTextField;
  /**
   * Loan2 Description field in *QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan2_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan2_description: prismicT.RichTextField;
  /**
   * Loan3 Image field in *QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan3_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan3_image: prismicT.ImageField<never>;
  /**
   * Loan3 Title field in *QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan3_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan3_title: prismicT.KeyTextField;
  /**
   * Loan3 Description field in *QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan3_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan3_description: prismicT.RichTextField;
  /**
   * Loan4 Image field in *QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan4_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan4_image: prismicT.ImageField<never>;
  /**
   * Loan4 Title field in *QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan4_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan4_title: prismicT.KeyTextField;
  /**
   * Loan4 Description field in *QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan4_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan4_description: prismicT.RichTextField;
  /**
   * Loan5 Image field in *QM LOANS*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan5_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  loan5_image: prismicT.ImageField<never>;
  /**
   * Loan5 Title field in *QM LOANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan5_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan5_title: prismicT.KeyTextField;
  /**
   * Loan5 Description field in *QM LOANS*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.loan5_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  loan5_description: prismicT.RichTextField;
  /**
   * Slice Zone field in *QM LOANS*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: qm_loans.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<QmLoansDocumentDataSlicesSlice>;
}
/**
 * Slice for *QM LOANS → Slice Zone*
 *
 */
type QmLoansDocumentDataSlicesSlice = never;
/**
 * QM LOANS document from Prismic
 *
 * - **API ID**: `qm_loans`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QmLoansDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<QmLoansDocumentData>,
    "qm_loans",
    Lang
  >;
/** Content for Realtors Resource documents */
interface RealtorsResourceDocumentData {
  /**
   * Title field in *Realtors Resource*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realtors_resource.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Text field in *Realtors Resource*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realtors_resource.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text: prismicT.KeyTextField;
  /**
   * Icon1 field in *Realtors Resource*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: realtors_resource.icon1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon1: prismicT.ImageField<never>;
  /**
   * Icon2 field in *Realtors Resource*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: realtors_resource.icon2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon2: prismicT.ImageField<never>;
}
/**
 * Realtors Resource document from Prismic
 *
 * - **API ID**: `realtors_resource`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RealtorsResourceDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<RealtorsResourceDocumentData>,
    "realtors_resource",
    Lang
  >;
/** Content for SEO documents */
interface SeoDocumentData {
  /**
   * Title field in *SEO*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Default Description field in *SEO*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.default_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  default_description: prismicT.KeyTextField;
  /**
   * Default Keywords field in *SEO*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.default_keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  default_keywords: prismicT.KeyTextField;
  /**
   * Default URL field in *SEO*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.default_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  default_url: prismicT.KeyTextField;
  /**
   * Default Image field in *SEO*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seo.default_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  default_image: prismicT.KeyTextField;
}
/**
 * SEO document from Prismic
 *
 * - **API ID**: `seo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SeoDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<SeoDocumentData>, "seo", Lang>;
/** Content for Sign Up documents */
interface SignUpDocumentData {
  /**
   * Title field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Subtitle field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismicT.KeyTextField;
  /**
   * Name field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Name Placeholder field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.name_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name_placeholder: prismicT.KeyTextField;
  /**
   * Lastname field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.lastname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  lastname: prismicT.KeyTextField;
  /**
   * Lastname Placeholder field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.lastname_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  lastname_placeholder: prismicT.KeyTextField;
  /**
   * Email field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  email: prismicT.KeyTextField;
  /**
   * Email Placeholder field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.email_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  email_placeholder: prismicT.KeyTextField;
  /**
   * Phone field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  phone: prismicT.KeyTextField;
  /**
   * Phone Placeholder field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.phone_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  phone_placeholder: prismicT.KeyTextField;
  /**
   * Body Text field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.body_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  body_text: prismicT.KeyTextField;
  /**
   * Submit Text field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.submit_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  submit_text: prismicT.KeyTextField;
  /**
   * Sent Message Text field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.sent_message_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  sent_message_text: prismicT.KeyTextField;
  /**
   * Checkbox Text field in *Sign Up*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up.checkbox_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  checkbox_text: prismicT.KeyTextField;
}
/**
 * Sign Up document from Prismic
 *
 * - **API ID**: `sign_up`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SignUpDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<SignUpDocumentData>,
    "sign_up",
    Lang
  >;
/** Content for Simulator documents */
interface SimulatorDocumentData {
  /**
   * Title field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Home Value Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.home_value_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  home_value_text: prismicT.KeyTextField;
  /**
   * Down Payment Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.down_payment_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  down_payment_text: prismicT.KeyTextField;
  /**
   * Interest Rate Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.interest_rate_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  interest_rate_text: prismicT.KeyTextField;
  /**
   * Loan Duration Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.loan_duration_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan_duration_text: prismicT.KeyTextField;
  /**
   * Property Tax Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.property_tax_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  property_tax_text: prismicT.KeyTextField;
  /**
   * Home Insurance Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.home_insurance_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  home_insurance_text: prismicT.KeyTextField;
  /**
   * Homeowners Association Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.homeowners_association_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  homeowners_association_text: prismicT.KeyTextField;
  /**
   * Principal Interest Only Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.principal_interest_only_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  principal_interest_only_text: prismicT.KeyTextField;
  /**
   * Loan Amount Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.loan_amount_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan_amount_text: prismicT.KeyTextField;
  /**
   * Total Interest Paid Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.total_interest_paid_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  total_interest_paid_text: prismicT.KeyTextField;
  /**
   * Monthly Tax Payment Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.monthly_tax_payment_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  monthly_tax_payment_text: prismicT.KeyTextField;
  /**
   * Monthly Home Insurance Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.monthly_home_insurance_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  monthly_home_insurance_text: prismicT.KeyTextField;
  /**
   * Total Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.total_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  total_text: prismicT.KeyTextField;
  /**
   * Payments Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.payments_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  payments_text: prismicT.KeyTextField;
  /**
   * Loan PayOff Date Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.loan_payoff_date_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  loan_payoff_date_text: prismicT.KeyTextField;
  /**
   * Estimated Total Monthly Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.estimated_total_monthly_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  estimated_total_monthly_text: prismicT.KeyTextField;
  /**
   * Get Your Loan Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.get_your_loan_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  get_your_loan_text: prismicT.KeyTextField;
  /**
   * Bottom Message Text field in *Simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simulator.bottom_message_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  bottom_message_text: prismicT.KeyTextField;
}
/**
 * Simulator document from Prismic
 *
 * - **API ID**: `simulator`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SimulatorDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<SimulatorDocumentData>,
    "simulator",
    Lang
  >;
export type AllDocumentTypes =
  | BuyingRefinancingProcessDocument
  | CircleGridInfoDocument
  | ContactDocument
  | FooterDocument
  | GeneralInformationDocument
  | HomepageDocument
  | MeetTeamDocument
  | MemberDocument
  | MenuDocument
  | NonQmLoansDocument
  | PreApprovalProcessDocument
  | QmLoansDocument
  | RealtorsResourceDocument
  | SeoDocument
  | SignUpDocument
  | SimulatorDocument;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      BuyingRefinancingProcessDocumentData,
      BuyingRefinancingProcessDocument,
      CircleGridInfoDocumentData,
      CircleGridInfoDocument,
      ContactDocumentData,
      ContactDocument,
      FooterDocumentData,
      FooterDocument,
      GeneralInformationDocumentData,
      GeneralInformationDocument,
      HomepageDocumentData,
      HomepageDocument,
      MeetTeamDocumentData,
      MeetTeamDocumentDataSlicesSlice,
      MeetTeamDocument,
      MemberDocumentData,
      MemberDocumentDataSlicesSlice,
      MemberDocument,
      MenuDocumentData,
      MenuDocumentDataMenuLinksItem,
      MenuDocument,
      NonQmLoansDocumentData,
      NonQmLoansDocument,
      PreApprovalProcessDocumentData,
      PreApprovalProcessDocument,
      QmLoansDocumentData,
      QmLoansDocumentDataSlicesSlice,
      QmLoansDocument,
      RealtorsResourceDocumentData,
      RealtorsResourceDocument,
      SeoDocumentData,
      SeoDocument,
      SignUpDocumentData,
      SignUpDocument,
      SimulatorDocumentData,
      SimulatorDocument,
      AllDocumentTypes,
    };
  }
}
