// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for CALCULATOR documents */
type CalculatorDocumentData = Record<string, never>;
/**
 * CALCULATOR document from Prismic
 *
 * - **API ID**: `calculator`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalculatorDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<CalculatorDocumentData>, "calculator", Lang>;
/** Content for SEO documents */
type SeoDocumentData = Record<string, never>;
/**
 * SEO document from Prismic
 *
 * - **API ID**: `seo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SeoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SeoDocumentData>, "seo", Lang>;
export type AllDocumentTypes = CalculatorDocument | SeoDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CalculatorDocumentData, CalculatorDocument, SeoDocumentData, SeoDocument, AllDocumentTypes };
    }
}
